# Generated by Django 5.2.5 on 2025-09-06 09:51

import django.core.validators
import django.db.models.deletion
import mailer.models.email_attachment_model
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBlacklistModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blacklists', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Blacklist',
                'verbose_name_plural': 'Email Blacklists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('body_plain', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=mailer.models.email_attachment_model.upload_to)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailer.emaillogmodel')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Name of the template', max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('alert', 'Alert'), ('report', 'Report'), ('welcome', 'Welcome'), ('invoice', 'Invoice'), ('reminder', 'Reminder'), ('marketing', 'Marketing'), ('password_reset', 'Password Reset'), ('verification', 'Email Verification'), ('order_status', 'Order Status Update'), ('notification', 'General Notification'), ('order_confirmation', 'Order Confirmation')], db_index=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True, help_text='Plain text fallback')),
                ('body_html', models.TextField(blank=True, help_text='HTML body with placeholders like {user_name}')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variables used in template')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='mailer_emai_name_b5234f_idx'), models.Index(fields=['template_type', 'is_active'], name='mailer_emai_templat_86aa76_idx')],
            },
        ),
        migrations.AddField(
            model_name='emaillogmodel',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='mailer.emailtemplatemodel'),
        ),
        migrations.AddIndex(
            model_name='emaillogmodel',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='mailer_emai_status_363417_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillogmodel',
            index=models.Index(fields=['recipient', 'created_at'], name='mailer_emai_recipie_3c2212_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillogmodel',
            index=models.Index(fields=['user', 'status'], name='mailer_emai_user_id_c2f363_idx'),
        ),
    ]
