# Generated by Django 5.2.5 on 2025-09-06 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillogmodel',
            name='sender',
            field=models.EmailField(default='pouriadrd@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
