# Generated by Django 5.2.8 on 2025-11-28 17:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique template name', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly template identifier', max_length=255, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('html_content', models.TextField(help_text='HTML content of the email. Use {{ variable }} for placeholders')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version (optional, auto-generated if empty)')),
                ('template_type', models.CharField(choices=[('custom', 'Custom Template'), ('predefined', 'Predefined Template')], default='custom', max_length=20)),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variables used in template')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='mailer_emai_slug_bbe4c4_idx'), models.Index(fields=['template_type', 'is_active'], name='mailer_emai_templat_86aa76_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending'), ('bounced', 'Bounced')], db_index=True, default='pending', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Variables used in the email')),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='mailer.emailtemplatemodel')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='mailer_emai_status_fdde07_idx'), models.Index(fields=['recipient_email', 'created_at'], name='mailer_emai_recipie_ad4039_idx')],
            },
        ),
    ]
