# Generated by Django 5.2.5 on 2025-09-07 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('email_otp_login', models.BooleanField(default=False, help_text='Allow login using email OTP if user is fully verified.')),
                ('phone_otp_login', models.BooleanField(default=False, help_text='Allow login using phone OTP if user is fully verified.')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], default='fa', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
                'indexes': [models.Index(fields=['user'], name='accounts_us_user_id_42811f_idx')],
            },
        ),
    ]
