# Generated by Django 5.2.8 on 2025-11-19 20:19

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Target email for OTP delivery.', max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('otp_type', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('verify_email', 'Verify email'), ('reset_password', 'Reset password')], default='login', help_text='Purpose of the OTP (login, register, etc.).', max_length=61)),
                ('salt', models.CharField(max_length=255)),
                ('code_hash', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='authenticat_email_7d7235_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('email', 'otp_type', 'is_used'), name='unique_active_otp_per_email_type')],
            },
        ),
    ]
