# Generated by Django 5.2.5 on 2025-09-17 13:33

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usecase', models.CharField(choices=[('email_2fa', 'Email 2FA'), ('email_verification', 'Email Verification')], default='email_2fa', max_length=20)),
                ('code_hash', models.CharField(max_length=256)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted', models.DateTimeField(default=datetime.datetime(2025, 9, 17, 13, 33, 48, 603036, tzinfo=datetime.timezone.utc))),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 9, 17, 13, 38, 48, 603045, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP code',
                'verbose_name_plural': 'OTP codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'usecase'], name='authenticat_user_id_fd0a02_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_d7aedb_idx')],
            },
        ),
    ]
