# Generated by Django 5.2.5 on 2025-09-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogCenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Log Center',
                'verbose_name_plural': 'Log Center',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'System Info',
                'verbose_name_plural': 'System Info',
                'managed': False,
            },
        ),
    ]
